### ISSUE TITLE
picture

### ISSUE THREAD

**Issue by Time-chaser** [wagenaartje/pinn4hcf#2]
How was the picture of the flow field in the report drawn? 
Can you provide the code to draw the graph? 
Or explain how the graphs were drawn

**Comment by wagenaartje** [comment]
In general I take the `x` and `y` coordinates of the reference set, use the trained model for predictions, exclude the data points inside the object, and plot one of the fields using [`matplotlib.pyplot.pcolor`](matplotlib.pyplot.pcolor). If you have a certain model in mind (e.g. [/curved/cpinn_phi_viscosity.py](https://github.com/wagenaartje/pinn4hcf/blob/main/curved/cpinn_phi_viscosity.py)) then I can provide some simplified code to visualize it.

**Comment by Time-chaser** [comment]
When using matplotlib.pyplot.pcolor to draw a graph, the edges of the object will be very rough and cannot be as smooth as the graph in the report. Have you undergone any special processing on the sampled coordinate points. Can you provide a drawing code for an example? For example (./surveyed/cpin_phi_visibility. py)

**Comment by wagenaartje** [comment]
That is correct, I use a trick to "hide" the jagged edges in the figure. I draw the outer perimeter of the object with a thick line using `matplotlib.pyplot.plot`. So for the curved object the code is similar to what is below. Note that you may need to vary the `linewidth` based on your figure size to hide the "jagged" contours of the object. 

```python
  p1 = torch.tensor([0.5, 0.0], device=device).reshape(-1,2)
  p2 = torch.tensor([1.0, 0.25], device=device).reshape(-1,2)
  p3 = torch.tensor([2.0, 0.25], device=device).reshape(-1,2)
  t = torch.linspace(0,1,1000, device=device).reshape(-1,1)
  B = (1-t)**2 * p1 + 2*(1-t)*t*p2 + t**2 * p3

  ax.plot(B[:,0], B[:,1], 'white', linewidth=2)
```


But I will provide the full code for an example figure sometime this week :smiley:

**Comment by Time-chaser** [comment]
Thank you. Looking forward to your full code.

**Comment by wagenaartje** [comment]
I have added [example_figure.py](https://github.com/wagenaartje/pinn4hcf/blob/main/example_figure.py), which shows how the density for `detached/cpinn_phi_viscosity_neumann` can be plotted. This example can easily be changed for the other models and plot variables. If you have any additional questions, feel free to let me know :smile:
